name: examples

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: ubuntu-latest
            arch: x86_64
            os: linux
            frida_version: "17.1.2"
          - runs_on: macos-latest
            arch: arm64
            os: macos
            frida_version: "17.0.5"
    runs-on: ${{ matrix.runs_on }}
    env:
      GOEXPERIMENT: cgocheck2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.x'
      - uses: ./.github/actions/install-frida-go-examples
      - uses: ./.github/actions/install-frida-devkit
        with:
          arch: ${{ matrix.arch }}
          os: ${{ matrix.os }}
          version: ${{ matrix.frida_version }}
      - run: |
          gcc -v; for example in ./frida-go-examples/*; do
            go build "$example"
          done
