name: linting

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  staticcheck:
    strategy:
      matrix:
        arch: [x86_64]
        os: [linux]
        frida_version: ["17.1.3"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: ./.github/actions/install-frida-devkit
        with:
          arch: ${{ matrix.arch }}
          os: ${{ matrix.os }}
          version: ${{ matrix.frida_version }}
      - run: go install honnef.co/go/tools/cmd/staticcheck@2024.1.1
      - run: ~/go/bin/staticcheck -checks all ./frida
